import {
  Bot,
  Brain,
  Sparkles,
  Code2,
  Terminal,
  GitBranch,
  Database,
  Server,
  Cloud,
  Cpu,
  Search,
  FileText,
  Image as ImageIcon,
  Video,
  Music,
  Mic,
  Palette,
  Wand2,
  Layers,
  Workflow,
  Zap,
  Repeat,
  Check,
  X,
  AlertTriangle,
  Shield,
  Lock,
  Key,
  User,
  Users,
  MessageSquare,
  Send,
  Mail,
  Globe,
  Link2,
  Settings,
  Wrench,
  TestTube,
  Gauge,
  BarChart3,
  TrendingUp,
  DollarSign,
  ShoppingCart,
  Book,
  GraduationCap,
  Lightbulb,
  Target,
  Rocket,
  Clock,
  Calendar,
  Clipboard,
  Download,
  Upload,
  RefreshCw,
  Eye,
  Filter,
  Scissors,
  Camera,
  Play,
  Smartphone,
  Monitor,
  House,
  Building2,
  Landmark,
  Scale,
  Banknote,
  Gavel,
  MapPin,
  Percent,
  Wallet,
  Handshake,
  FilePen,
  Receipt,
  type LucideIcon,
} from "lucide-react";
import type { IconKey } from "@/content/types";

export const ICON_MAP: Record<IconKey, LucideIcon> = {
  bot: Bot,
  brain: Brain,
  sparkles: Sparkles,
  code: Code2,
  terminal: Terminal,
  "git-branch": GitBranch,
  database: Database,
  server: Server,
  cloud: Cloud,
  cpu: Cpu,
  search: Search,
  "file-text": FileText,
  image: ImageIcon,
  video: Video,
  music: Music,
  mic: Mic,
  palette: Palette,
  wand: Wand2,
  layers: Layers,
  workflow: Workflow,
  zap: Zap,
  repeat: Repeat,
  check: Check,
  x: X,
  alert: AlertTriangle,
  shield: Shield,
  lock: Lock,
  key: Key,
  user: User,
  users: Users,
  message: MessageSquare,
  send: Send,
  mail: Mail,
  globe: Globe,
  link: Link2,
  settings: Settings,
  wrench: Wrench,
  "test-tube": TestTube,
  gauge: Gauge,
  chart: BarChart3,
  "trending-up": TrendingUp,
  dollar: DollarSign,
  "shopping-cart": ShoppingCart,
  book: Book,
  "graduation-cap": GraduationCap,
  lightbulb: Lightbulb,
  target: Target,
  rocket: Rocket,
  clock: Clock,
  calendar: Calendar,
  clipboard: Clipboard,
  download: Download,
  upload: Upload,
  refresh: RefreshCw,
  eye: Eye,
  filter: Filter,
  scissors: Scissors,
  camera: Camera,
  play: Play,
  smartphone: Smartphone,
  monitor: Monitor,
  home: House,
  building: Building2,
  landmark: Landmark,
  scale: Scale,
  banknote: Banknote,
  gavel: Gavel,
  "map-pin": MapPin,
  percent: Percent,
  wallet: Wallet,
  handshake: Handshake,
  "file-pen": FilePen,
  receipt: Receipt,
};

export function ContentIcon({
  name,
  className,
}: {
  name: IconKey;
  className?: string;
}) {
  const Icon = ICON_MAP[name] ?? Sparkles;
  return <Icon className={className} aria-hidden />;
}
